#是否开启3X3区块检测功能
NineChunk: false

#是否开启5X5区块检测功能（需要先开启3X3）
NineChunkImprove: false


#优化版选项启用
#利：减少占用
#弊：高度检测严重削弱，方块放置和差超出既不检测
#实际上已经不需要了，最新版已经支持并列检测，大幅度降低占用
Optimization: false

YAxis: 32


#是否检测方块Tile
Tile: true

#是否检测植魔花
Botania: true