name: CustomChunkLimit
main: com.tany.customchunklimit.Main
version: 1.5.0
author: tany
depend: [ProtocolLib,NBTAPI]
commands:
  customchunklimit:
    usage: /customchunklimit
    aliases: [ccls]
permissions: 
  ccl.list: 
    default: true
  ccl.op: 
    default: op
