name: CustomChunkLimit
main: pers.tany.customchunklimit.Main
version: 1.6.0
author: tany
description: 区块限制方块放置
depend: [ProtocolLib,NBTAPI]
commands:
  customchunklimit:
    usage: /customchunklimit
    aliases: [ccl]
permissions: 
  ccl.list: 
    default: true
  ccl.op: 
    default: op