name: CustomChunkLimit
main: pers.tany.customchunklimit.Main
version: 1.5.3
author: tany
depend: [ProtocolLib,NBTAPI]
commands:
  customchunklimit:
    usage: /customchunklimit
    aliases: [ccl]
permissions: 
  ccl.list: 
    default: true
  ccl.op: 
    default: op