name: CustomChunkLimit
main: pers.tany.customchunklimit.CustomChunkLimit
version: ${project.version}
author: tany
api-version: 1.16
depend: [ProtocolLib,NBTAPI]
commands:
  customchunklimit:
    usage: /customchunklimit
    aliases: [ccl]
permissions: 
  ccl.list: 
    default: true
  ccl.op: 
    default: op